;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname |Exercise 5.1.1|) (read-case-sensitive #t) (teachpacks ((lib "guess.rkt" "teachpack" "htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "guess.rkt" "teachpack" "htdp")) #f)))
;; reply s : symbol --> symbol
;; this function accepts a symbol provided by a user and, if the user-provided symbol matches 'HowAreYou,
;; gives in return a symbol generated by the function.

(define (reply s)
  (cond
    [(symbol=? s 'GoodMorning) 'Hi]
    [(symbol=? s 'HowAreYou?) 'Fine]
    [(symbol=? s 'GoodAfternoon) 'INeedANap]
    [(symbol=? s 'GoodEvening) 'BoyAmITired]))

(reply 'HowAreYou?)
"should be"
(cond
  [(symbol=? 'HowAreYou? 'GoodMorning ) 'Hi]
  [(symbol=? 'HowAreYou? 'HowAreYou?) 'Fine]
  [(symbol=? 'HowAreYou? 'GoodAfternoon) 'INeedANap]
  [(symbol=? 'HowAreYou 'GoodEvening) 'BoyAmITired])
"should be"
(cond
    [false 'Hi]
    [(symbol=? 'HowAreYou? 'HowAreYou?) 'Fine]
    [(symbol=? 'HowAreYou? 'GoodAfternoon) 'INeedANap]
    [(symbol=? 'HowAreYou 'GoodEvening) 'BoyAmITired])
"should be"
(cond
    [(symbol=? 'HowAreYou? 'HowAreYou?) 'Fine]
    [(symbol=? 'HowAreYou? 'GoodAfternoon) 'INeedANap]
    [(symbol=? 'HowAreYou 'GoodEvening) 'BoyAmITired])
"should be"
(cond
    [true 'Fine]
    [(symbol=? 'HowAreYou? 'GoodAfternoon) 'INeedANap]
    [(symbol=? 'HowAreYou 'GoodEvening) 'BoyAmITired])
"should be"
'Fine

(symbol=? (reply 'GoodMorning) 'Hi)
(symbol=? (reply 'HowAreYou?) 'Fine)
(symbol=? (reply 'GoodAfternoon) 'INeedANap)
(symbol=? (reply 'GoodEvening) 'BoyAmITired)


